# Generated by Django 5.2.8 on 2025-11-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nko',
            name='logo',
        ),
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.FloatField(default=55.7558),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.FloatField(default=37.6173),
        ),
    ]
