# Generated by Django 5.2.8 on 2025-11-16 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0003_nko_logo_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nko',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
